### ISSUE TITLE
Add shortcut

### ISSUE THREAD

**Issue by shijimasoft** [SirMrShyGuy/AutoClicker#1]
**clicks activation** with **key shortcut** (from keyboard or mouse) is missing.
would be nice to have this feature ^^

**Comment by SirMrShyGuy** [comment]
The feature does exist it is hard coded to the F19 key. It can be changed by editing what the keyboard monitor is looking for in the AppDelegate. Unfortunately at this point I don't have any plans to update this project any further.

**Comment by shijimasoft** [comment]
I understand, thank you 😊
